Use JSONP in OpenLayers example
Geovation/labelgun pull request #9
Opened 2017-01-11 16:16 UTC by tomchadwin

Allows local use #7

2017-01-11 16:17 UTC, tomchadwin commented
Again, please check - in some ways this is slightly more complex code, but still simple enough. Judgement call whether to merge.

2017-01-11 22:09 UTC, JamesLMilner requested changes
Looks great, can you just change the snake case variables to camel case i.e. format_geojson to formatGeojson etc.

2017-01-11 22:18 UTC, tomchadwin commented
Oh, gladly. Prefer camel myself, but had copied this code from elsewhere.

2017-01-12 14:09 UTC, JamesLMilner approved these changes

2017-01-12 14:09 UTC, merged